### PR TITLE
Early support for calling dotnet via CMake

### PR DESCRIPTION
**Pull request by cspiegel**

### CODE REVIEW

**Comment by cspiegel** [comment]
The latest commit moves the build of FrankenDrift into CMake for Mac, too.

However, whether via this branch or the original integration branch, my FrankenDrift doesn't run on Mac:

```
2024-09-04 15:12:01.185 FrankenDrift.GlkRunner.Gargoyle[36669:109853] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSString stringWithUTF8String:]: NULL cString'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007ff813805deb __exceptionPreprocess + 242
        1   libobjc.A.dylib                     0x00007ff813566b34 objc_exception_throw + 48
        2   Foundation                          0x00007ff8144e3198 __destroy_helper_block_e8_32o40r + 0
        3   libgarglk.dylib                     0x0000000110459b0b _Z7wininitPiPPc + 107
        4   libgarglk.dylib                     0x00000001103e3471 garglk_startup + 113
        5   FrankenDrift.GlkRunner.Gargoyle     0x000000010f64b234 FrankenDrift.GlkRunner.Gargoyle + 1262132
        6   FrankenDrift.GlkRunner.Gargoyle     0x000000010f64bf3d FrankenDrift.GlkRunner.Gargoyle + 1265469
        7   FrankenDrift.GlkRunner.Gargoyle     0x000000010f64be2b FrankenDrift.GlkRunner.Gargoyle + 1265195
        8   FrankenDrift.GlkRunner.Gargoyle     0x000000010f9e254c FrankenDrift.GlkRunner.Gargoyle + 5027148
        9   dyld                                0x000000011301252e start + 462
)
```
I'm not familiar with debugging on Mac (trying gdb as I would on another Unix doesn't work), but I'll see what I can figure out.

**Comment by cspiegel** [comment]
Ok. This is in a decent state.

The AppImage, DEB, RPM, and Mac build scripts can now do FrankenDrift.

Windows is still yet to be done.  I think I have a VM with a development environment, but I'll have to take some time to figure it out.

**Comment by awlck** [comment]
> However, whether via this branch or the original integration branch, my FrankenDrift doesn't run on Mac:

IIRC this error occurs in the Mac/Cocoa garglk frontend when you attempt to run an interpreter directly instead of through the launcher. It's not specific to FrankenDrift.

**Comment by cspiegel** [comment]
> > However, whether via this branch or the original integration branch, my FrankenDrift doesn't run on Mac:
> 
> IIRC this error occurs in the Mac/Cocoa garglk frontend when you attempt to run an interpreter directly instead of through the launcher. It's not specific to FrankenDrift.

Yep, looks like that's the case.  I tried through the launcher, and it didn't work (a Gargoyle window pops up, but it just says "press any key to exit").  When the interpreter failed to run at the command-line I assumed that was the cause, but it's a red herring.  I'm not sure why it's not working, but I'll see what I can find out.

I'm also having trouble with Windows.  I have a dev environment with LLVM/Clang and vcpkg, but CMake claims clang-cl can't create binaries.

I'm attaching an untested-on-windows patch that you might be able to try; this doesn't handle cross-compiling to ARM, but should be a starting point.  With luck, all platforms will be able to just do the right thing if WITH_FRANKENDRIFT is provided.

[win.txt](https://github.com/user-attachments/files/16894965/win.txt)

**Comment by awlck** [comment]
> I'm attaching an untested-on-windows patch that you might be able to try; this doesn't handle cross-compiling to ARM, but should be a starting point.

Yes, this seems to work fine on Windows.

**Comment by awlck** [comment]
This all seems to be working fine in my testing. Is there anything else major that needs to be done, or can this be merged?

**Comment by cspiegel** [comment]
The only thing left to do for the CMake integration is adding Windows ARM support to CMake, and the remove the call to `dotnet` from `winbuildrelease.ps1`.  But you can merge this in as-is, and see if you can get those two working in your branch.

I know I had Windows working with CMake/Clang back when you originally added the MSVC pull requests so I think I can get it working again, but as of right now I can't do that part.

**Comment by awlck** [comment]
Thanks! I've adjusted the Windows build script, at least for x86-64.

**Pull request merged**
